package com.sunbeam.main;

public enum EMainMenu {
	LOG_OUT, EDIT_PROFILE, CHANGE_PASSWORD, WRITE_REVIEW, EDIT_REVIEW, DISPLAY_ALL_MOVIES, DISPLAY_ALL_REVIEWS,
	DISPLAY_MY_REVIEWS, DISPLAY_REVIEWS_SHARED_WITH_ME, SHARE_REVIEW, DELETE_REVIEW, WRONG;
}
